name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build via Maven
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2

    - name: Set up JDK
      uses: actions/setup-java@v4.7.0
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: Build with Maven
      run: mvn package -B --file pom.xml

    - name: Upload build artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: ViaLimbo
        path: target/ViaLimbo-*.jar